[book]
title = "程序员入门指南"
#authors = ["本书编写组"]
language = "zh-CN"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://gitee.com/tsagaanbar/Newly-Programmer-ABC"
mathjax-support = true
